# android sdk
if [ -d "$HOME/Library/Android/sdk" ]; then
	export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
	export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
	export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
fi

# bin
if [ -d "$HOME/bin" ]; then
	export PATH=$PATH:$HOME/bin
	export PATH="/usr/local/sbin:$PATH"
fi

# cargo
if [ -d "$HOME/.cargo" ]; then
	. "$HOME/.cargo/env"
fi

# pnpm
if [ -d "$HOME/.local/share/pnpm" ]; then
	export PNPM_HOME="$HOME/.local/share/pnpm"
	case ":$PATH:" in
  	*":$PNPM_HOME:"*) ;;
  	*) export PATH="$PNPM_HOME:$PATH" ;;
	esac
fi

# vitasdk
if [ -d "$HOME/bin/vitasdk" ]; then
	export VITASDK="$HOME/bin/vitasdk"
	export PATH="$VITASDK/bin:$PATH"
fi

# fnm
if which fnm >/dev/null 2>&1; then
  eval "$(fnm env --use-on-cd)"
fi

# move into fish
local calledWithinFish=$(ps -p $$ -T -o "comm" | grep -q 'fish' &>/dev/null; echo $?)
local hasNoExecutionString=$(test -z ${ZSH_EXECUTION_STRING}; echo $?)
if [[ $calledWithinFish -ne 0 && $hasNoExecutionString && -o interactive ]]
then
	exec fish
fi
